/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WinLog */

#ifndef _Included_WinLog
#define _Included_WinLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WinLog
 * Method:    openEventLog
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_WinLog_openEventLog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WinLog
 * Method:    closeEventLog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_WinLog_closeEventLog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     WinLog
 * Method:    takeLogs
 * Signature: (JJI)[Ljava/util/Properties;
 */
JNIEXPORT jobjectArray JNICALL Java_WinLog_takeLogs
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     WinLog
 * Method:    getOldestRecord
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_WinLog_getOldestRecord
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
